name: dish_of_the_world
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.0
  provider: ^6.0.0
  go_router: ^12.0.0
  shared_preferences: ^2.0.0
  
  # UI dependencies
  google_fonts: ^6.0.0
  flutter_animate: ^4.0.0
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.0.0
  page_transition: ^2.0.0
  
  # Network and caching
  cached_network_image: ^3.0.0
  
  # Utilities
  intl: ^0.20.2
  timeago: ^3.0.0
  easy_debounce: ^2.0.0
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.0.0
  from_css_color: ^2.0.0
  json_path: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: Emerald
      fonts:
        - asset: assets/fonts/Emerald.ttf
    - family: IMaterialLight
      fonts:
        - asset: assets/fonts/iMaterialLight.ttf